/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/templates/**/*.html',
    './app/static/js/**/*.js',
  ],
  // Safelist: clases construidas dinámicamente en JS (modal variant, toast variant)
  // que el escáner estático no detectaría. Sin esto, el purge las elimina.
  safelist: [
    // Modal variants (ui.js -> VARIANT_CONFIG)
    'text-danger-400', 'bg-danger-500/10', 'border-danger-500/30',
    'bg-danger-600', 'hover:bg-danger-500',
    'text-warning-400', 'bg-warning-500/10', 'border-warning-500/30',
    'bg-warning-600', 'hover:bg-warning-500',
    'text-primary-400', 'bg-primary-500/10', 'border-primary-500/30',
    // Toast variants (ui.js -> TOAST_VARIANTS)
    'border-success-500', 'text-success-100', 'shadow-success-900/20',
    'border-danger-500',  'text-danger-100',  'shadow-danger-900/20',
    'border-warning-500', 'text-warning-100', 'shadow-warning-900/20',
    'border-info-500',    'text-info-100',    'shadow-info-900/20',
  ],
  theme: {
    extend: {
      colors: {
        // Theme-aware tokens (resolved from CSS vars set per [data-theme])
        primary: {
          50:  'rgb(var(--color-primary-50)  / <alpha-value>)',
          100: 'rgb(var(--color-primary-100) / <alpha-value>)',
          200: 'rgb(var(--color-primary-200) / <alpha-value>)',
          300: 'rgb(var(--color-primary-300) / <alpha-value>)',
          400: 'rgb(var(--color-primary-400) / <alpha-value>)',
          500: 'rgb(var(--color-primary-500) / <alpha-value>)',
          600: 'rgb(var(--color-primary-600) / <alpha-value>)',
          700: 'rgb(var(--color-primary-700) / <alpha-value>)',
          800: 'rgb(var(--color-primary-800) / <alpha-value>)',
          900: 'rgb(var(--color-primary-900) / <alpha-value>)',
          950: 'rgb(var(--color-primary-950) / <alpha-value>)',
        },
        canvas: {
          50:  'rgb(var(--color-canvas-50)  / <alpha-value>)',
          100: 'rgb(var(--color-canvas-100) / <alpha-value>)',
          200: 'rgb(var(--color-canvas-200) / <alpha-value>)',
          300: 'rgb(var(--color-canvas-300) / <alpha-value>)',
          400: 'rgb(var(--color-canvas-400) / <alpha-value>)',
          500: 'rgb(var(--color-canvas-500) / <alpha-value>)',
          600: 'rgb(var(--color-canvas-600) / <alpha-value>)',
          700: 'rgb(var(--color-canvas-700) / <alpha-value>)',
          800: 'rgb(var(--color-canvas-800) / <alpha-value>)',
          900: 'rgb(var(--color-canvas-900) / <alpha-value>)',
          950: 'rgb(var(--color-canvas-950) / <alpha-value>)',
        },
        // Semantic state tokens (theme-independent)
        success: {
          50:  'rgb(var(--color-success-50)  / <alpha-value>)',
          100: 'rgb(var(--color-success-100) / <alpha-value>)',
          200: 'rgb(var(--color-success-200) / <alpha-value>)',
          300: 'rgb(var(--color-success-300) / <alpha-value>)',
          400: 'rgb(var(--color-success-400) / <alpha-value>)',
          500: 'rgb(var(--color-success-500) / <alpha-value>)',
          600: 'rgb(var(--color-success-600) / <alpha-value>)',
          700: 'rgb(var(--color-success-700) / <alpha-value>)',
          800: 'rgb(var(--color-success-800) / <alpha-value>)',
          900: 'rgb(var(--color-success-900) / <alpha-value>)',
          950: 'rgb(var(--color-success-950) / <alpha-value>)',
        },
        danger: {
          50:  'rgb(var(--color-danger-50)  / <alpha-value>)',
          100: 'rgb(var(--color-danger-100) / <alpha-value>)',
          200: 'rgb(var(--color-danger-200) / <alpha-value>)',
          300: 'rgb(var(--color-danger-300) / <alpha-value>)',
          400: 'rgb(var(--color-danger-400) / <alpha-value>)',
          500: 'rgb(var(--color-danger-500) / <alpha-value>)',
          600: 'rgb(var(--color-danger-600) / <alpha-value>)',
          700: 'rgb(var(--color-danger-700) / <alpha-value>)',
          800: 'rgb(var(--color-danger-800) / <alpha-value>)',
          900: 'rgb(var(--color-danger-900) / <alpha-value>)',
          950: 'rgb(var(--color-danger-950) / <alpha-value>)',
        },
        warning: {
          50:  'rgb(var(--color-warning-50)  / <alpha-value>)',
          100: 'rgb(var(--color-warning-100) / <alpha-value>)',
          200: 'rgb(var(--color-warning-200) / <alpha-value>)',
          300: 'rgb(var(--color-warning-300) / <alpha-value>)',
          400: 'rgb(var(--color-warning-400) / <alpha-value>)',
          500: 'rgb(var(--color-warning-500) / <alpha-value>)',
          600: 'rgb(var(--color-warning-600) / <alpha-value>)',
          700: 'rgb(var(--color-warning-700) / <alpha-value>)',
          800: 'rgb(var(--color-warning-800) / <alpha-value>)',
          900: 'rgb(var(--color-warning-900) / <alpha-value>)',
          950: 'rgb(var(--color-warning-950) / <alpha-value>)',
        },
        info: {
          50:  'rgb(var(--color-info-50)  / <alpha-value>)',
          100: 'rgb(var(--color-info-100) / <alpha-value>)',
          200: 'rgb(var(--color-info-200) / <alpha-value>)',
          300: 'rgb(var(--color-info-300) / <alpha-value>)',
          400: 'rgb(var(--color-info-400) / <alpha-value>)',
          500: 'rgb(var(--color-info-500) / <alpha-value>)',
          600: 'rgb(var(--color-info-600) / <alpha-value>)',
          700: 'rgb(var(--color-info-700) / <alpha-value>)',
          800: 'rgb(var(--color-info-800) / <alpha-value>)',
          900: 'rgb(var(--color-info-900) / <alpha-value>)',
          950: 'rgb(var(--color-info-950) / <alpha-value>)',
        },
      },
      fontFamily: {
        sans:    ['Inter', 'sans-serif'],
        heading: ['Playfair Display', 'serif'],
        mono:    ['Fira Code', 'monospace'],
      },
    },
  },
  plugins: [],
};
