"""Add accounting models and update numeric types

Revision ID: 48ccad46b412
Revises: 314484f549ed
Create Date: 2025-11-22 13:37:44.955986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ccad46b412'
down_revision = '314484f549ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_cesta_de_compra')
    with op.batch_alter_table('cesta_de_compra', schema=None) as batch_op:
        batch_op.alter_column('producto_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=8),
               existing_nullable=False)

    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.alter_column('producto_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=8),
               existing_nullable=False)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=8),
               existing_nullable=False)
        batch_op.alter_column('proveedor_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=8),
               existing_nullable=False)
        batch_op.alter_column('precio_unitario',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costo', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
        batch_op.alter_column('precio',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('tasa_de_descuento',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('iva',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('usuario',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('contrasenya_hash',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_usuario_usuario', ['usuario'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint('uq_usuario_usuario', type_='unique')
        batch_op.alter_column('contrasenya_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('usuario',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.alter_column('iva',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('tasa_de_descuento',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('costo')

    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('precio_unitario',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('proveedor_id',
               existing_type=sa.String(length=8),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('usuario_id',
               existing_type=sa.String(length=8),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('producto_id',
               existing_type=sa.String(length=8),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('cesta_de_compra', schema=None) as batch_op:
        batch_op.alter_column('producto_id',
               existing_type=sa.String(length=8),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.create_table('_alembic_tmp_cesta_de_compra',
    sa.Column('id', sa.VARCHAR(length=8), nullable=False),
    sa.Column('usuario_id', sa.VARCHAR(), nullable=False),
    sa.Column('producto_id', sa.VARCHAR(length=8), nullable=False),
    sa.Column('cantidad', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
